// Copyright 2006-2017 ClickTale Ltd., US Patent Pending
// Generated on: 3/12/2017 7:23:54 AM (UTC 3/12/2017 12:23:54 PM)

window.ClickTaleGlobal = window.ClickTaleGlobal || {};
ClickTaleGlobal.scripts = ClickTaleGlobal.scripts || {};
ClickTaleGlobal.scripts.filter = ClickTaleGlobal.scripts.filter || (function () {
	var recordingThreshold = Math.random() * 100;

	return {
		isRecordingApproved: function(percentage) {
			return recordingThreshold <= percentage;
		}
	}
})();
	
		
// Copyright 2006-2017 ClickTale Ltd., US Patent Pending
// PID: 443
// Generated on: 3/12/2017 7:23:54 AM (UTC 3/12/2017 12:23:54 PM)



/*browsers exclusion start*/function doOnlyWhen(toDoHandler, toCheckHandler, interval, times, failHandler) {
    if ((!toDoHandler) || (!toCheckHandler)) return;
    if (typeof interval == "undefined") interval = 1000;
    if (typeof times == "undefined") times = 20;

    if (--times < 0 && typeof failHandler === 'function') {
        failHandler();
        return;
    }
    if (toCheckHandler()) {
        toDoHandler();
        return;
    }

    setTimeout(function () { doOnlyWhen(toDoHandler, toCheckHandler, interval, times); }, interval);
}
doOnlyWhen(function () { if (window.ClickTaleSettings.PTC.okToRunPCC) { (function(){var d=!0,e=!1,j=this;var k,l,m,n;function o(){return j.navigator?j.navigator.userAgent:null}n=m=l=k=e;var p;if(p=o()){var aa=j.navigator;k=0==p.indexOf("Opera");l=!k&&-1!=p.indexOf("MSIE");m=!k&&-1!=p.indexOf("WebKit");n=!k&&!m&&"Gecko"==aa.product}var q=k,r=l,s=n,t=m,u;
a:{var v="",w;if(q&&j.opera)var x=j.opera.version,v="function"==typeof x?x():x;else if(s?w=/rv\:([^\);]+)(\)|;)/:r?w=/MSIE\s+([^\);]+)(\)|;)/:t&&(w=/WebKit\/(\S+)/),w)var y=w.exec(o()),v=y?y[1]:"";if(r){var z,A=j.document;z=A?A.documentMode:void 0;if(z>parseFloat(v)){u=""+z;break a}}u=v}var C={};
function D(a){var b;if(!(b=C[a])){b=0;for(var c=(""+u).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=(""+a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),g=Math.max(c.length,f.length),B=0;0==b&&B<g;B++){var fa=c[B]||"",ga=f[B]||"",ha=RegExp("(\\d*)(\\D*)","g"),ia=RegExp("(\\d*)(\\D*)","g");do{var i=ha.exec(fa)||["","",""],h=ia.exec(ga)||["","",""];if(0==i[0].length&&0==h[0].length)break;b=((0==i[1].length?0:parseInt(i[1],10))<(0==h[1].length?0:parseInt(h[1],10))?-1:(0==i[1].length?0:parseInt(i[1],
10))>(0==h[1].length?0:parseInt(h[1],10))?1:0)||((0==i[2].length)<(0==h[2].length)?-1:(0==i[2].length)>(0==h[2].length)?1:0)||(i[2]<h[2]?-1:i[2]>h[2]?1:0)}while(0==b)}b=C[a]=0<=b}return b}var E={};function F(){E[9]||(E[9]=r&&!!document.documentMode&&9<=document.documentMode)};!r||F();!r||F();r&&D("8");!t||D("528");s&&D("1.9b")||r&&D("8")||q&&D("9.5")||t&&D("528");!s||D("8");function G(a,b,c,f,g){a&&b&&("undefined"==typeof c&&(c=1E3),"undefined"==typeof f&&(f=20),0>--f?"function"===typeof g&&g():b()?a():setTimeout(function(){G(a,b,c,f,g)},c))};function H(a,b){var c=Element.prototype;H=function(a,b){return H.d.call(a,b)};H.d=c.matches||c.webkitMatchesSelector||c.mozMatchesSelector||c.msMatchesSelector;return H(a,b)}function I(a,b){I=Element.prototype.closest?function(a,b){return Element.prototype.closest.call(a,b)}:function(a,b){for(;a&&!H(a,b);)a=a.parentElement;return a};return I(a,b)};function ba(a){function b(){c||(c=d,a())}var c=e;"complete"===document.readyState||"interactive"===document.readyState?b():document.addEventListener&&document.addEventListener("DOMContentLoaded",b,e)}
function J(a,b,c,f,g){"string"===typeof a?(a=document.querySelectorAll(a),Array.prototype.forEach.call(a,function(a){J(a,b,c,f,g)})):a instanceof Array||a instanceof NodeList?Array.prototype.forEach.call(a,function(a){J(a,b,c,f,g)}):a.addEventListener(b,function(a,b,c,f,g){return function(i){if("function"===typeof c)c.apply(this,arguments),g&&a.removeEventListener(b,arguments.callee,e);else{var h=I(i.target,c);h&&(f.apply(h,arguments),g&&a.removeEventListener(b,arguments.callee,e))}}}(a,b,c,f,g),
e)}function ca(a,b){document.addEventListener("mouseup",function(c){a===c.target&&b();document.removeEventListener("mouseup",arguments.callee,e)},e)}function da(a,b){function c(c){document.removeEventListener("touchend",arguments.callee,e);a===c.target&&b()}document.addEventListener("touchend",c,e);document.addEventListener("touchmove",function(a){document.removeEventListener("touchmove",arguments.callee,e);document.removeEventListener("touchend",c,e)},e)}
function K(a,b){var c=L();c&&(K=c.m?da:ca,K(a,b))};function M(a){if(window.CSS&&"function"===typeof window.CSS.escape)M=function(a){return window.CSS.escape.call(window.CSS,a)};else{var b=/([\0-\x1f\x7f]|^-?\d)|^-$|[^\x80-\uFFFF\w-]/g,c=function(a,b){return b?"\x00"===a?"\ufffd":a.slice(0,-1)+"\\"+a.charCodeAt(a.length-1).toString(16)+" ":"\\"+a};M=function(a){return(a+"").replace(b,c)}}return M(a)};function N(a,b){"function"===typeof ClickTaleEvent&&(b?N.b[a]!==d&&(N.b[a]=d,ClickTaleEvent(a)):ClickTaleEvent(a))}N.b={};function O(){var a=P;"function"===typeof ClickTaleRegisterFormSubmit&&ClickTaleRegisterFormSubmit(a)}function Q(){var a=P;"function"===typeof ClickTaleRegisterFormSubmitSent&&ClickTaleRegisterFormSubmitSent(a)}function ea(){var a=P;"function"===typeof ClickTaleRegisterFormSubmitFailure&&(a?ClickTaleRegisterFormSubmitFailure(a):ClickTaleRegisterFormSubmitFailure())}
function ja(){"function"===typeof ClickTaleFormDisableAll&&ClickTaleFormDisableAll()}function ka(a,b,c){return"function"===typeof window.ClickTaleLogicalForm?window.ClickTaleLogicalForm(a,b,c):0}function la(a){"function"===typeof window.ClickTaleRegisterElementAction&&(ClickTaleRegisterElementAction("mouseover",a),ClickTaleRegisterElementAction("click",a))}function ma(a,b){var c={},f;for(f in a)c[f]=a[f];c.target=b;c.srcElement=b;la(c)}window.ClickTaleDetectAgent&&window.ClickTaleDetectAgent()&&window.ClickTaleDetectAgent();
function na(a,b){"object"==typeof a&&"string"==typeof b&&(window.ClickTaleContext&&-1!=document.referrer.indexOf(location.hostname)&&window.parent.ct&&window.parent.ct.ElementAddressing&&"function"===typeof window.parent.ct.ElementAddressing.setCustomElementID?window.parent.ct.ElementAddressing.setCustomElementID(a,b):(window.ClickTaleSetCustomElementID=window.ClickTaleSetCustomElementID||function(a,b){a.ClickTale=a.ClickTale||{};a.ClickTale.CustomID=b},window.ClickTaleSetCustomElementID(a,b)))}
function oa(){Array.prototype.forEach.call(document.querySelectorAll("[id]"),function(a){if(!H(a,'input[type="hidden"]')){var b=a.getAttribute("id");b.match(/(?:\r|\n)/)&&"function"===typeof ClickTaleNote&&ClickTaleNote("ctlib.api.SetCustomElementIdDuplicates: ids with line break found!");var a=document.querySelectorAll('[id="'+M(b)+'"]'),c=pa;1<a.length&&!c[b]&&(c[b]=d,Array.prototype.forEach.call(a,function(a,c){na(a,b.replace(/(\r|\n|\r\n|\s+)+/g,"_").replace(/\W/g,"_")+"_"+c)}))}})}var pa={};
function L(){if("function"===typeof ClickTaleDetectAgent){var a=ClickTaleDetectAgent();if(a)return L=function(){return a},L()}return null}function qa(a){if("function"===typeof ClickTaleRegisterTouchAction){var b=a.getBoundingClientRect();ClickTaleRegisterTouchAction(a,b.left+document.body.scrollLeft,b.top+document.body.scrollTop)}}
function ra(){var a;if(!a){a="mousedown";if("boolean"!=typeof R){var b=L();b&&(R=b.m)}R&&(a="touchstart")}J(document,a,"img, a, button, textarea, input, select",function(a){var b=a.target,g=this;K(b,function(a,b){return function(){if(H(this,"button,a,textarea")&&this!=a)R?qa(this):ma(b,this);else if(!R){var c=function(){};document.addEventListener("click",function(a){return c=function(b){b.target===a&&(S=d);document.removeEventListener("click",arguments.callee,e)}}(a),e);setTimeout(function(){S||
la(b);document.removeEventListener("click",c,e);S=void 0},200)}}.bind(g)}(b,a))})}var R,S;var T=N;function sa(){var a=U.toString();"function"===typeof ClickTaleField&&ClickTaleField("isMobile",a)}function V(a,b){return a instanceof Element?b instanceof Element?a===b:H(a,b):e}var ta=K;var W="",X=document.location.pathname.toLowerCase(),U=e,Y="on",P;
function ua(){oa();if(/\/petdetail\/\d+\/?/.exec(X))W="Pet Profile Page",T("Onload | Pet Profile Page");else if(/\/adoption-inquiry\/\d+\/?$/i.exec(X)){W="Adoption Inquiry Form";T("Onload | Adoption Inquiry Form");var a="form[name=animal_adoption_inquiry_guest]";if(Z(jQuery(a))){ja();var b=jQuery(a+" input, "+a+" select, "+a+" textarea, "+a+" button").toArray(),c="Guest Inquiry",a=jQuery(a+" button[type=submit]");Z(b)&&c&&Z(a)&&(P=ka(c,b,[a[0]]))}0<jQuery("a[href=#animal_adoption_inquiry_guest_captcha]:visible").length&&
T("Onload | Adoption Inquiry Form | Captcha Error Message")}else/\/adoption-inquiry\/\d+\/success/i.exec(X)?T("Onload | Adoption Inquiry Form Success Page"):/\/user\/did\-you\-adopt\/apply\/[^/]+?\/?$/i.exec(X)?(W="Adoption Kit Form",T("Onload | Adoption Kit Form"),a="form[name=offer_did_you_adopt_guest_application]",Z(jQuery(a))&&(ja(),b=jQuery(a+" input, "+a+" select, "+a+" textarea, "+a+" button").toArray(),c="Guest Kit",a=jQuery(a+" button[type=submit]"),Z(b)&&c&&Z(a)&&(P=ka(c,b,[a[0]]))),0<jQuery("a[href=#offer_did_you_adopt_guest_application_captcha]:visible").length&&
T("Onload | Adoption Inquiry Form | Captcha Error Message")):/\/user\/did\-you\-adopt\/apply\/[^/]+?\/success/i.exec(X)&&T("Onload | Adoption Kit Form Success Page")}function Z(a){return 0<a.length?d:e}
function va(){if(!window.ClickTaleFirstPCCGo){window.ClickTaleFirstPCCGo=d;var a=L();a&&(U=a.m,sa());ua();"function"!=typeof jQuery.fn.on&&(Y="delegate");a=U?"touchstart":"mousedown";a="on"===Y?[a,"button[type=submit],a#sponsor-button,a.js-petDetail-adoptMeBtn,aside#available-pets,div#recentpets-container,article#editorial-mod,button#find-pets-btn,section.pet-profile-container a[href^=mailto],button#login,input#animal_adoption_inquiry_guest_emailOptIn_sponsor,input#animal_adoption_inquiry_guest_emailOptIn_petfinder,input#offer_did_you_adopt_guest_application_emailOptIn_sponsor,input#offer_did_you_adopt_guest_application_emailOptIn_petfinder,button#adoption_inquiry_submit,button#offer_did_you_adopt_guest_application_submit,div.inquireMedia-body a[href^=mailto]"]:["button[type=submit],a#sponsor-button,a.js-petDetail-adoptMeBtn,aside#available-pets,div#recentpets-container,article#editorial-mod,button#find-pets-btn,section.pet-profile-container a[href^=mailto],button#login,input#animal_adoption_inquiry_guest_emailOptIn_sponsor,input#animal_adoption_inquiry_guest_emailOptIn_petfinder,input#offer_did_you_adopt_guest_application_emailOptIn_sponsor,input#offer_did_you_adopt_guest_application_emailOptIn_petfinder,button#adoption_inquiry_submit,button#offer_did_you_adopt_guest_application_submit,div.inquireMedia-body a[href^=mailto]",
a];jQuery(document)[Y](a[0],a[1],function(a){var c=a.target;jQuery(a);var f=jQuery(this);ta(c,function(a){return function(){V(this,"button#find-pets-btn")?T("Action | Activates a Pet Search"):V(this,"section.pet-profile-container a[href^=mailto],div.inquireMedia-body a[href^=mailto]")&&T("Action | Clicks on contact email address");switch(W){case "Adoption Inquiry Form":V(this,"form[name=animal_adoption_inquiry_guest] button[type=submit]")?(O(),Q(),setTimeout(function(){0<jQuery("label.label_error:visible").length&&
(ea(),T("Action | Adoption Inquiry Form | On-Submit Validation Triggered"))},2E3),jQuery("input#animal_adoption_inquiry_guest_emailOptIn_sponsor:visible,input#animal_adoption_inquiry_guest_emailOptIn_petfinder:visible")[0].checked?T("Action | Adoption Inquiry Form | Purina Communication Box Checked"):T("Action | Adoption Inquiry Form | Purina Communication Box Unchecked")):V(this,"button#login")&&T('Action | Adoption Inquiry Form | Clicks "Log In"');break;case "Adoption Kit Form":V(this,"form[name=offer_did_you_adopt_guest_application] button[type=submit]")?
(O(),Q(),setTimeout(function(){0<jQuery("label.label_error:visible").length&&(ea(),T("Action | Adoption Kit Form | On-Submit Validation Triggered"))},2E3),jQuery("input#offer_did_you_adopt_guest_application_emailOptIn_sponsor:visible,input#offer_did_you_adopt_guest_application_emailOptIn_petfinder:visible")[0].checked?T("Action | Adoption Kit Form | Purina Communication Box Checked"):T("Action | Adoption Kit Form | Purina Communication Box Unchecked")):V(this,"button#login")&&T('Action | Adoption Kit Form | Clicks "Log In"');
break;case "Pet Profile Page":V(this,"a#sponsor-button")?T("Action | Pet Profile | Clicks \u201cSponsor Me\u201d"):V(this,"a.js-petDetail-adoptMeBtn")?T("Action | Pet Profile | Clicks \u201cAsk About Pet\u201d"):V(this,"aside#available-pets")?T("Action | Pet Profile | Clicks Within \u201cOther Pets at this Organization\u201d"):V(this,"div#recentpets-container")?T("Action | Pet Profile | Clicks Within \u201cRecently Viewed Pets\u201d"):V(this,"article#editorial-mod")&&T("Action | Pet Profile | Clicks Within \u201cMore About Adoption\u201d")}}.bind(a[0])}(f,
c,a))});jQuery("ul.petSearch-filter input[type=text]").on("keyup",function(a){13==a.keyCode&&a.target.value&&T("Action | Activates a Pet Search")});a="on"===Y?["blur","form[name=animal_adoption_inquiry_guest] input[type=text],form[name=animal_adoption_inquiry_guest] textarea,form[name=offer_did_you_adopt_guest_application] input[type=text],form[name=offer_did_you_adopt_guest_application] textarea"]:["form[name=animal_adoption_inquiry_guest] input[type=text],form[name=animal_adoption_inquiry_guest] textarea,form[name=offer_did_you_adopt_guest_application] input[type=text],form[name=offer_did_you_adopt_guest_application] textarea",
"blur"];jQuery(document)[Y](a[0],a[1],function(){switch(W){case "Adoption Inquiry Form":setTimeout(function(){0<jQuery("label.label_error:visible").length&&T("Action | Adoption Inquiry Form | In-Line Validation Triggered")},500);break;case "Adoption Kit Form":setTimeout(function(){0<jQuery("label.label_error:visible").length&&T("Action | Adoption Kit Form | In-Line Validation Triggered")},500)}})}}
(function(a){function b(){2==++window.okToStartOn2&&a()}window.okToStartOn2=0;ba(function(){b()});if("function"==typeof ClickTaleIsRecording&&ClickTaleIsRecording()===d)b();else{var c=window.ClickTaleOnRecording||function(){};window.ClickTaleOnRecording=function(){b();return c.apply(this,arguments)}}})(function(){ra();G(va,function(){return window.jQuery&&("function"===typeof jQuery.fn.on||"function"===typeof jQuery.fn.delegate)?d:e},250,40)});})();} }, function () { return !!(window.ClickTaleSettings && window.ClickTaleSettings.PTC && typeof window.ClickTaleSettings.PTC.okToRunPCC != 'undefined'); }, 500, 20);
